{"name": "test_login_a_courier_fake_data_error", "status": "passed", "description": "Попытка авторизации курьера с использованием несуществующих данных. Ожидание в ответе кода с сообщением об ошибке", "attachments": [{"name": "stdout", "source": "6101535f-5322-4730-8ee4-9f9253776921-attachment.txt", "type": "text/plain"}], "start": 1708173819130, "stop": 1708173819708, "uuid": "14c0565d-443c-46aa-b499-cd97356e595e", "historyId": "8a1a13e6a5dd94dc0e96b45d1b267fd7", "testCaseId": "8a1a13e6a5dd94dc0e96b45d1b267fd7", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_a_courier_fake_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "16552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}