{"name": "test_create_double_courier_error", "status": "passed", "description": "Попытка создания второго курьера с данными, которые уже были использованы при создании курьера в фикстуре", "attachments": [{"name": "stdout", "source": "97c3a67a-a9ae-4842-8833-cdc0f0d9029b-attachment.txt", "type": "text/plain"}], "start": 1708173800184, "stop": 1708173800700, "uuid": "7afeecb3-becb-4bb1-9017-f78ce4beabe2", "historyId": "b7b482dbbc7693c6cf72cc8276b44ac5", "testCaseId": "b7b482dbbc7693c6cf72cc8276b44ac5", "fullName": "tests.test_creating_courier.TestAddCourier#test_create_double_courier_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_courier"}, {"name": "subSuite", "value": "TestAddCourier"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "16552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_courier"}]}