{"name": "test_login_a_courier_fake_data_error", "status": "passed", "description": "Попытка авторизации курьера с использованием несуществующих данных. Ожидание в ответе кода с сообщением об ошибке", "attachments": [{"name": "stdout", "source": "ca645f25-9611-4680-8c25-c71d6a8aa634-attachment.txt", "type": "text/plain"}], "start": 1707327629936, "stop": 1707327630561, "uuid": "0b295889-a843-41c4-b9bc-beccb6e40653", "historyId": "8a1a13e6a5dd94dc0e96b45d1b267fd7", "testCaseId": "8a1a13e6a5dd94dc0e96b45d1b267fd7", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_a_courier_fake_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "5500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}